### ISSUE TITLE
Which license does the source code have?

### ISSUE THREAD

**Issue by MichaelHoelzl** [OnfireNetwork/dialogui#7]
Hi
Which license does the source code have? MIT, APACHE, LGPL.. etc. ?
thanks

**Comment by JulianFun123** [comment]
I think the Apache License like (Because it's also used in an other Project by us): https://github.com/OnfireNetwork/godfather/blob/master/LICENSE

**Comment by JanHolger** [comment]
sorry for this late answer. i didn't know that i didn't add a license file for dialogui. there were people who actually "stole" my code from my server before and i didn't lawsuit them so feel free to do it aswell (: added a license file anyway for your safety
